<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\HexagonalExemplo.Dominio\HexagonalExemplo.Dominio.csproj" />
    <ProjectReference Include="..\..\src\HexagonalExemplo.Aplicacao\HexagonalExemplo.Aplicacao.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
