<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HexagonalExemplo.Dominio\HexagonalExemplo.Dominio.csproj" />
    <ProjectReference Include="..\HexagonalExemplo.Aplicacao\HexagonalExemplo.Aplicacao.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MassTransit" Version="8.4.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
